apiVersion : apps/v1
kind: Deployment

metadata:
  name: fastapi-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: manikandanbnair/fastapi-backend:v7
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8000
          envFrom:
          - configMapRef:
              name: postgres-config
        readinessProbe:
          httpGet:
            path: /db-health
            port: 8000
        livenessProbe:
        
          httpGet:
            path: /live
            port: 8000