---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          image: manikandanbnair/fastapi-backend:v7
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /live
              port: 8000
          name: fastapi
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /db-health
              port: 8000